DROP TABLE IF EXISTS identity_demo_2;

CREATE TABLE identity_demo_2(
	id BIGINT GENERATED BY DEFAULT as IDENTITY,
	firstName TEXT,
	lastName TEXT
);

INSERT INTO identity_demo_2 (firstName, lastName) 
VALUES 
    ('John', 'Doe'),
    ('Alice', 'Smith'),
    ('Bob', 'Johnson');

-- When we are using GENERATED BY DEFAULT it will allow any random value to be inserted without needing OVERRIDE SYSTEM VALUE
-- But this will still break the sequence
INSERT INTO identity_demo_2 (id, firstName, lastName) 
VALUES 
    (9, 'Kiran', 'Dash');

-- To reset the sequence first you can get the current sequence
SELECT pg_get_serial_sequence('identity_demo_2', 'id');
-- and then reset the sequence to the new value
SELECT setval('public.identity_demo_2_id_seq', (select max(id) from identity_demo_2));

INSERT INTO identity_demo_2 (firstName, lastName) 
VALUES 
    ('Sourav', 'B'),
    ('Sourav', 'C'),
    ('Sourav', 'D'),
    ('Sourav', 'E'),
    ('Sourav', 'F'),
    ('Sourav', 'G');

SELECT * FROM identity_demo_2;

