-- second bound or > does not use bitmap index scan but runs a sequence scan
-- this is happening because of indexing selectivity
explain SELECT * FROM indexing_demo_users where birthdate > '1982-08-26';

-- calculating selectivity is a little trickier for the second bound logic with >
SELECT COUNT(*) FROM indexing_demo_users where birthdate > '1982-08-26'; -- 935309
-- In the above case adding index will not help because the number of rows is too many ex: more than half of the table so postgres skips it and goes to the table instead
 
SELECT COUNT(*) FROM indexing_demo_users where birthdate < '1982-08-26'; -- 64619
-- In this case adding index will help because the number of rows is a good size and postgres thinks it is useful to go to and find the result

-- Note: Postgres does not run query to find the count and determine the candidacy but it uses the underlying statistics (which are generated using auto vaccume etc) to determine whether to scan through index DS or not 

-- These underlying statistics are auto generated by postgres but it might not auto generate if we do a bulk update. in which case we will have to update it manually. we will see in future how to do that
